kind: pipeline
type: docker
name: Déploiement du site Hugo sur S3

variables:
  S3_BUCKET: drone-restaurant-s3
  AWS_REGION: us-east-1

trigger:
  branch:
    - main
  event:
    - push

steps:
  - name: build-hugo-site
    image: klakegg/hugo:ext-alpine
    environment:
      HUGO_BASEURL: http://${S3_BUCKET}.s3-website.${AWS_REGION}.amazonaws.com
    commands:
      - hugo --baseURL ${HUGO_BASEURL}
  - name: deploy-to-s3
    image: plugins/s3
    depends_on:
      - build-hugo-site
    settings:
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      aws_session_token:
        from_secret: aws_session_token
      region: ${AWS_REGION}
      bucket: ${S3_BUCKET}
      source: public/
      delete: true
    when:
          event: push
          branch:
            - main
            - master