# --- Ancre de configuration réutilisable ---
# Modifiez vos variables ici.
s3_config: &s3_config
  S3_BUCKET: drone-restaurant-s3
  AWS_REGION: us-east-1

kind: pipeline
type: docker
name: Déploiement du site Hugo sur S3

# Le déclencheur global pour le push sur la branche main.
trigger:
  branch:
    - main
  event:
    - push

steps:
  # --- ÉTAPE 1: Construire le site Hugo ---
  - name: build-hugo-site
    image: klakegg/hugo:ext-alpine
    environment:
      # On injecte les variables de l'ancre.
      <<: *s3_config
      # On construit l'URL de base pour corriger les liens CSS.
      HUGO_BASEURL: http://${S3_BUCKET}.s3-website.${AWS_REGION}.amazonaws.com
    commands:
      # Hugo génère le site dans le dossier par défaut './public'.
      - hugo

  # --- ÉTAPE 2: Déployer sur S3 ---
  - name: deploy-to-s3
    image: plugins/s3
    # S'assure que l'étape de build est terminée.
    depends_on:
      - build-hugo-site
    # On rend les variables de l'ancre disponibles pour cette étape.
    environment:
      <<: *s3_config
    settings:
      # Les secrets restent inchangés.
      aws_access_key_id:
        from_secret: aws_access_key_id
      aws_secret_access_key:
        from_secret: aws_secret_access_key
      aws_session_token:
        from_secret: aws_session_token
      
      # Le plugin lira les variables depuis l'environnement de l'étape.
      region: ${AWS_REGION}
      bucket: ${S3_BUCKET}
      
      source: public/
      delete: true