# ---
hugo_env: &hugo_env
  BASE_URL: http://drone-restaurant-s3.s3-website-us-east-1.amazonaws.com/

kind: pipeline
type: docker
name: hugo-to-s3-deploy

steps:
  - name: hugo-build
    image: peaceiris/hugo:v0.65.3-mod
    environment:
      <<: *hugo_env
    commands:
      - hugo --baseURL $BASE_URL

  - name: deploy-to-s3
    image: amazon/aws-cli:2.31.17 
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY:
        from_secret: AWS_SECRET_ACCESS_KEY
      AWS_DEFAULT_REGION: us-east-1
      AWS_SESSION_TOKEN:
        from_secret: AWS_SESSION_TOKEN
    commands:
      - aws s3 cp public/ s3://drone-restaurant-s3/ --recursive --cache-control max-age=86400

    when:
      event: push
      branch:
        - main
        - master